version: '3'

services:
  price_it_auth :
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${DOCKER_SERVER_PORT}:${LOCAL_SERVER_PORT}
    volumes:
      - .:/usr/src/price_it_app
      - /usr/src/app/node_modules
